/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class com_speedcam_OpenCVDetection */

using namespace cv;

#ifndef _Included_com_speedcam_OpenCVDetection
#define _Included_com_speedcam_OpenCVDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_speedcam_OpenCVDetection
 * Method:    signDetection
 * Signature: (J)V
 */

 void detectObject(Mat& frame);

JNIEXPORT void JNICALL Java_com_speedcam_OpenCVDetection_signDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
